### ISSUE TITLE
Förderplan

### ISSUE THREAD

**Issue by FritzBaumann** [WAW-WS16/Organization#11]
Hallo zusammen,
1. Kann es mehrere Förderpläne pro Schüler geben und wie wird das dann auf der Website angezeigt. Gibt es einen Auswahlscreen auf dem man die Förderpläne einzeln anklicken kann oder scrollt man durch eine nach Förderplänen sortierte Kompetenzliste und links oben wird nur angezeigt über welchem Förderplan man gerade scrollt?
2. Wird bei Kompetenzen, die in einem Förderplan sind, auch angezeigt in welchem Förderplan, z.B. durch Hover über der Kompetenz, sie vermerkt sind?
Mit freundlichen Grüßen
Fritz

**Comment by jdoose** [comment]
Hallo,

ja, es kann mehrere Förderpläne für einen Schüler geben, auch gleichzeitig. So soll er bspw. in Mathe einen Förderplan durcharbeiten und in Deutsch einen anderen.

Im "Förderplanmenü" sieht man eine Liste der aktuell für den/dir Schüler*in gültigen Förderpläne:
![2016-10-24_13-28-56](https://cloud.githubusercontent.com/assets/3868618/19644030/db7133b0-99ed-11e6-81f4-9355cbea0a1b.png)

Ja, in dem Hover-/Info-Text wird immer angezeigt, aus welchem Förderplan die Inhalte&Tätigkeiten stammen. In der Form:

```
Förderplanname 1:
Text aus Förderplan 1

Förderplanname 2:
Text aus Förderplan 2
```
