### ISSUE TITLE
Grafiken und Style Guide für mobile version

### ISSUE THREAD

**Issue by JesusJones92** [WAW-WS16/Organization#13]
Hallo,

wann können wir denn mit den Grafiken rechnen? Kapitelgrafiken sind erstmal zu vernachlässigen, aber die Grafiken fürs Menü wären schon mal praktisch. 

Und gibt es auch einen styleguide für die mobile version?

**Comment by jdoose** [comment]
Die Grafiken werden aktuell fertig gemacht und geschnitten.
Vermutlich sind sie Mitte/Ende nächster Woche fertig.
So lange müsstet Ihr Euch mit Dummy-Platzhalter-Grafiken aushelfen.

Braucht Ihr abseits von der abstrakten Darstellung der mobilen Version im Mockup (S. 6ff) noch weiteres?

**Comment by CodeKittey** [comment]
Update:
Die Grafiken (ein kompletter images Folder)  werden im Laufe des Wochenendes aller spaetestens aber am Montag Vormittag veroeffentlicht!

**Comment by JesusJones92** [comment]
Hallo,

sind die Grafiken schon irgendwo verfügbar?

**Comment by CodeKittey** [comment]
Die Grafiken sind unter dem Repo 
https://github.com/WAW-WS16/images.git
ab sofort Verfuegbar.
Erklaerungen dazu (falls notwendig) gibt es am Mittwoch.
