### ISSUE TITLE
Fragen zum Styleguide

### ISSUE THREAD

**Issue by joschmid** [WAW-WS16/Organization#18]
Hallo zusammen,

beim Durchschauen des neuen Styleguides sind noch ein paar Fragen aufgetreten

1) Welche Farbe hat der Rahmen der Benuternamen- und Passwortfelder bei inaktiv und aktiv?

2) Auf Folie 8 im Stlyeguide ist der Footer anders dargestellt als auf den anderen Folien. In diesem Footer sind noch die Inhalte des LoginFooters drin. Soll dieses beim hovern über den Footer angezeigt werden oder ist dies nur ein Fehler im Styleguide?

3) Müssen die Illustrationen fix sein und nur die Sprechblasen lassen sich scrollen oder scrollen die Bilder mit und werden dann, sobald das Bild verschwunden ist, neu eingespielt?

4) Auf Folie 12 des Styleguides ist im Dropdown-Menü die Schriftfarbe beim Hovern weiß und beim nicht-hovern dunkel. Auf Folie 22 sind die Farben im Dropdown-Menü immer weiß und werden nicht dunkel. Ist dies Absicht?

5) Muss der Footer fix am unteren Rand des Bildschirmes sein oder soll er immer am Ende der Seite angezeigt werden? Heißt sobald man den Bildschirm zoomt, bleibt der Footer immer unten an der Seite und der Abstand zwischen Loginbutton und Footer bleiben gleich oder zoomt sich der Footer mit und der Abstand zwischen Loginbutton und Footer wird kleiner?

Mfg
Johannes

**Comment by jdoose** [comment]
Hallo Johannes,

zu 1. ich würde sagen:
inaktiv: CHECK! Grau
aktiv: CHECK! Violett

Zu 2. Gut beobachtet!
Ich würde sagen, es es ist ein Fehler und es gelten die anderen Footer, NICHT der von Seite 8.

Zu 3.
Die Bilder scrollen einfach mit, das dürfte auch das einfachste zu implementieren sein.
Nochmal zur Erinnerung:
Es gibt mehrere Illustrationen.
Für jeden 5er-Kompetenz-Block gibt es zwei Kompetenzen, eine für links, eine für rechts.
D.h. hat ein Kapitel 100 Kompetenzen gibt es ingesamt 100 / 5 * 2 Illustrationen.
Block 1, Kompetenz 1 - 5: linke Illustration + rechte Illustration
Block 2, Kompetenz 6 - 10: linke Illustration + rechte Illustration

Aktuell gibt es nur eine Illustration, die immer wiederholt wird zu Demonstrationszwecken.

Zu 4.
Wow, Du Adlerauge, wiederrum gut gesehen!
Ich würde sagen, auf S. 22 und 23 ist ein Fehler, die nicht-aktiven Menüeinträge haben ebenfalls eine dunkle Schriftfarbe

Zu 5.
Der Footer ist fix am unteren Rand des Bildschirms. 
Besonders schön wäre es natürlich, wenn das Verhältnis des Abstands vom Content nach oben bzw. unten gleich bleiben würde. Das betrifft aber sowieso nur die Loginseite sowie Passwort ändern, etc.
Wenn das zu kompliziert ist reicht es aus, wenn der Abstand nach oben hin gleich bleibt und sich dadurch der Abstand des Contents zum Footer hin erhöht beim Zoomen.
Soweit verständlich?
