### ISSUE TITLE
Scrollbuttons-/ Put-Avatar-ID Probleme

### ISSUE THREAD

**Issue by MSchabel** [WAW-WS16/Organization#30]
Hallo zusammen,

uns sind noch folgende Fehler aufgefallen bzw. Fragen eingefallen:

1. Die Bilder der verschiedenen Scroll-Buttons in den einzelnen Chaptern haben die selbe Farbe, wie der Hintergrund (weakcolor) das heißt von den Buttons ist immer nur der weiße Pfeil sichtbar. Einzige Ausnahme ist das "Fremdsprachen"-Kapitel.

2. Beim Ausführen der Put-Methode Avatar-ID bekommt man eine positive Rückmeldung, beim abrufen ist die ID allerdings unverändert. Dadurch kann man die Funktion (ähnlich wie beim Passwort ändern) nicht richtig testen. 

3. noch eine Frage, wenn man die Delete-Methode wirklich ausführen würde, wäre unser User dann tatsächlich gelöscht/ gesperrt?

Mit freundlichen Grüßen

Einhornragout

**Comment by CodeKittey** [comment]
1. ja das ist vollkommen in Ordnung

2. Naja durch die erfolgreiche Meldung "wuerde erfolgreich geloescht", "wurde erfolreich geanedert" scheint es erfolgreich gewesen zu sein. Da muesst ihr euch um die anderen Dinge keine Sorgen machen ;)

3. Wenn das backend kein Prototyp ist sondern richtig implementiert ist, wird der User wirklich geloescht. Aber auch hier bekommt ihr lediglich eine erfolgsmeldung und koennt euch noch weiterhin mit dem User anmelden.
