### ISSUE TITLE
Förderplan Styleguide

### ISSUE THREAD

**Issue by MSchabel** [WAW-WS16/Organization#31]
Hey zusammen, 

mir ist gerade noch aufgefallen, dass wir keinen Styleguide dafür haben, was passieren soll wenn man im Dropdown-Menu Förderpläne auf einen solchen klickt.

Wird das noch nachgeliefert oder bleibt das erstmal ohne Funktion?

lg Martin

**Comment by jdoose** [comment]
Ich verstehe die Frage leider nicht ganz ;)

Wenn man einen Förderplan auswählt, dann wird die dahinter liegende Ansicht mit den Kompetenzen aus dem Förderplan aktualisiert. (S. 23 des StyleGuides).

Oder habe ich es falsch verstanden?

**Comment by joschmid** [comment]
Hallo Jens,

also unser Problem ist, dass wir nicht wissen, was passieren soll, wenn man auf einen der Förderpläne aus dem Dropdown-Menü klickt. Also was für eine Seite geladen werden soll. Von der API bekommen wir lediglich die Informationen ID, Name und Thema (Siehe Screenshot)

![image](https://cloud.githubusercontent.com/assets/17764718/22782386/248f167e-eec7-11e6-95e0-59a671f10e42.png)

Ebenso wissen wir nicht, woher wir die Infos des Förderplans bekommen, die beim hovern kommen sollen. Diese sind nicht in der API enthalten. Zudem müsste doch irgendwo stehen, zu welchen Kompetenzen der Förderplan gehört.

![image](https://cloud.githubusercontent.com/assets/17764718/22782420/5c4e3158-eec7-11e6-8d47-270386916c57.png)

Für uns ist eben der Förderplan insgesamt noch nicht ganz klar, aber ich hoffe ich konnte unser Problem nun ein wenig genauer beschreiben

Gruß
Johannes

**Comment by CodeKittey** [comment]
Dann ruft mal die Route auf:
/api/V1/educationalPlan/1

Dann erhaltet ihr folgendes Array:

```
[
  {
    "id": 0,
    "educationalPlanId": 1,
    "competences": [
      {
        "competenceId": 51,
        "note": "proident ipsum occaecat enim voluptate",
        "order": 1
      },
      {
        "competenceId": 236,
        "note": "do deserunt esse in minim",
        "order": 2
      },
      {
        "competenceId": 85,
        "note": "duis dolore reprehenderit cillum mollit",
        "order": 3
      },
```

Ihr erhaltet eine Aufslistung aller Kompetenzen die sich in dem Foerderplan befinden ;)
