### ISSUE TITLE
Fragen zu Profil löschen und Klassendaten 

### ISSUE THREAD

**Issue by VivianMachlis** [WAW-WS16/Organization#8]
Wenn der Schüler sein Profil löschen möchte, muss er sein Passwort als Bestätigung eingeben oder kommt dann einfach die Frage "Profil wirklich löschen? -ja -nein"? Und wenn er das Profil gelöscht hat, ist das Profil ja nicht wirklich weg, sondern er hat nur keinen Zugriff mehr darauf. Wie könnte er dann wieder Zugriff darauf bekommen? 
Welche Klassendaten werden nochmal angezeigt wenn man auf den Icon klickt? 
Gruß Vivi :)

**Comment by jdoose** [comment]
Hallo Vivi, 

das sind gute Fragen.

* Beim Profillöschen sollte als Bestätigung in der Tat ncohmal das Passwort eingegeben werden.
* Das Profil wird anschließend in der Datenbank markiert, dass es keinen Schülerzugriff mehr gibt
* Der Schüler/die Schülerin bekommt nur wieder Zugriff darauf, wenn ein Lehrer*in dies in der Lehreransicht wieder frei schaltet

* Welches Icon meinst Du? Das Klassensymbol? Wenn ja: Ein Schüler hat eine "Stammklasse", das ist ein besonderes Attribut in der Klassenauflistung der REST-API. Und diese Klassendaten werden in der Klassenvisitenkarte angezeigt.

**Comment by VivianMachlis** [comment]
Vielen Dank für die schnelle Antwort. 
Zum Klassensymbol wollte ich wissen was das genau für Klassendaten sind, die in der Visitenkarte angezeigt werden. Im Mockup ist ein Beispiel für die Visitenkarte der Schuldaten (Straße,Nr,PLZ...) aber nicht für die Klassendaten.

**Comment by jdoose** [comment]
Ah, verstehe.
Dort wird aktuell die "Stammklasse" eines Schülers angezeigt mit 
* Icon
* Name, bspw. "2a"
* Name des/der Klassenlehrers/in

Alle Informationen werden über die REST-Schnittstelle abrufbar sein.

Als Vorabbeispiel:

![2016-10-20_20-22-49](https://cloud.githubusercontent.com/assets/3868618/19572559/0877b1ce-9703-11e6-8383-83353f5320d8.png)

**Comment by VivianMachlis** [comment]
Alles klar danke :)
