### ISSUE TITLE
Menü und Kompetenzlisten

### ISSUE THREAD

**Issue by 1531169** [WAW-WS16/Organization#9]
Hallo zusammen,

1.) wenn man auf die Kompetenzliste klickt, wird dann ein erweitertes Menü erscheinen in dem die Kapitel aufgelistet werden und dann kann man ein Kapitel auswählen, dass dann auf einer neuen Seite mit den einzelnen Kompetenzen angezeigt wird?

2.) Wenn man auf ein Kapitel geklickt hat, wird im Mockup rechts und links Illustationen aufgezeigt. Was ist genau gemeint mit Illustrationen und werden auf beiden Seiten die gleichen Illustrationen gezeigt?

2.1) Diese Blöcke sollen nur so hoch sein wie 5 Blasen. Wird das dann nur für die ersten 5 Blasen gemacht? Was ist wenn mehr als 5 Blasen darin sind?

3.) Der Menüpunkt "Das bin ich"/Sternsymbol der Funktionsleiste, zeigt alle Kompetenzen des jeweiligen Schülers auf. Dabei wurde im Mockup beschrieben, dass es einen Zusatzmenüpunkt gibt (Alle Kompetenzen). Bedeutet das, dass beim Klick auf Funktionsmenü->Sternsymbol das Menü wieder erweitert wird und dir Kapitel angezeigt werden, in denen der Schüler schon Kompetenzen hat? Und beim Klick auf das jeweilige Kapitel die von ihm erreichten Kompetenzen aufgelistet bekommt. Der Zusatzpunkt soll dann einfach alle Kompetenzen auflisten undabhängig von den Kapitel?

PS: hoffentlich verständlich beschrieben :sweat_smile: 

Grüße
Cedric

**Comment by jdoose** [comment]
Hallo Cedric,

Zu 1.)
Das habe ich leider nicht ganz verstanden.
Ich probiere es mal anders rum, bitte Bescheid geben, falls ich daneben liege...
Klickt man auf das linke oder das rechte Icon im Funktionsmenü (Seite 2), dann klappt ein Menü auf mit der Kapitelliste (Seite 5, rechts Menü). Aus diesem wählt man dann das anzuzeigende Kapitel aus. Anschließend ändert sich die Ansicht und es werden die Kompetenzen aus diesem Kapitel angezeigt.

zu 2.) und 2.1)
Eine Illustration ist "nur" ein Bild, eine Grafik. Links und rechts werden unterschiedliche Illustrationen angezeigt.
Welches Bild angezeigt wird, kann später über die Schnittstelle abgefragt werden.
Pro "5er-Kompetenz-Block" können zwei Grafiken festgelegt werden: links und rechts.
Sieht dann irgendwie so aus:

```
{
	[
		{
			"StartCompetence": 0,
			"IllustrationLeft": "/img/illustration/chapter01/0-left.png",
			"IllustrationRight": "/img/illustration/chapter01/0-right.png",
		},
		{
			"StartCompetence": 5,
			"IllustrationLeft": "/img/illustration/chapter01/1-left.png",
			"IllustrationRight": "/img/illustration/chapter01/1-right.png",
		},
		{
			"StartCompetence": 10,
			"IllustrationLeft": "/img/illustration/chapter01/2-left.png",
			"IllustrationRight": "/img/illustration/chapter01/2-right.png",
		},
		...
	]
}
```
(Nur PseudoCode - bitte auf keinen Fall mit dieser Struktur rechnen!)

zu 3:)
Der Punkt "Alle Kompetenzen" zeigt alle Kompetenzen an, unabhängig vom Kapitel, in dem sich die Kompetenz befindet. In diesem Punkt sieht man also einfach alle Kompetenzen, die der Schüler/die Schülerin hat untereinander aufgetragen. Die Kompetenzen können dabei aus allen Kapiteln kommen.
Deswegen lassen sich bei diesem Punkt auch weder Illustrationen noch eine Kapitelfarbe bestimmen. Als Farbe wird dann eine vordefinierte feste Hintergrundfarbe verwendet.

Konnte ich soweit alles verständlich beschreiben?

**Comment by 1531169** [comment]
Zu 1.)
Ok genau das meinte ich.

Zu 2.)
Gibt es eine Begrenzung, wie viele Kompetenzen bzw. Blasen auf der Seite angezeigt werden sollen?

Zu 3.)
Auch soweit geklärt.

Vielen Dank.

**Comment by jdoose** [comment]
Zu 2.)
Bei Funktion "Kompetenzliste"/"Meine Kompetenzen":
Alle Kompetenzen innerhalb eines Kapitels, Pro Kapitel sind das aktuell folgende Anzahlen:

Kapitel | Anzahl
------- | ----------
DAS BIN ICH! | 30
ICH UND DIE ANDEREN | 60
DIE WELT UM MICH HERUM: MEINUNGEN UND RECHTE | 20
DIE WELT UM MICH HERUM: NATUR UND TECHNIK | 30
DIE WELT UM MICH HERUM: ZEIT UND GESCHICHTE | 20
DIE WELT UM MICH HERUM: LÄNDER UND KULTUREN | 29
DIE WELT UM MICH HERUM: KOMMUNIKATION UND MEDIEN | 20
ICH WERDE SELBSTSTÄNDIG: KÖRPER UND GESUNDHEIT | 40
ICH WERDE SELBSTSTÄNDIG: MOBILITÄT UND FREIZEIT | 20
ICH WERDE SELBSTSTÄNDIG: HAUSHALT UND FINANZEN | 40
SICH BEWEGEN: SPIELEN | 40
SICH BEWEGEN: SCHWIMMEN | 10
SICH BEWEGEN: RENNEN, SPRINGEN, WERFEN | 10
SICH BEWEGEN: TURNEN | 10
SICH BEWEGEN: TANZEN UND TRAINIEREN | 20
LERNEN | 80
ARBEITEN | 40
GESTALTEN UND ERSCHAFFEN: THEATER SPIELEN | 10
GESTALTEN UND ERSCHAFFEN: MUSIK MACHEN | 20
GESTALTEN UND ERSCHAFFEN: MATERIALIEN BEARBEITEN | 60
GESTALTEN UND ERSCHAFFEN: KREATIVITÄT ENTFALTEN | 40
SPRECHEN | 60
FREMDSPRACHE | 30
LESEN | 90
SCHREIBEN | 60
MESSEN: GELD | 20
MESSEN: ZEIT | 20
MESSEN: LÄNGE | 20
MESSEN: GEWICHT & VOLUMEN | 19
LÖSUNGEN FINDEN | 60
ZÄHLEN UND RECHNEN | 119
FORM UND RAUM ENTDECKEN | 59

Ist "Meine Kompetenzen" -> "Alle Kompetenzen" ausgewählt, dann können das theoretisch alle sein.

Bei einem Förderplan können theoretisch alle Kompetenzen enthalten sein. Allerdings: Der größte Förderplan, den ich bisher gesehen habe, hatte pro Schüler 39 Kompetenzen.
